### ISSUE TITLE
NULL Value

### ISSUE THREAD

**Issue by gusadelic** [brainfoolong/cryptojs-aes-php#1]
Hi, I was so excited when I found your work, because I've been looking all over for a solution to be able to use crypto.js output with php.  However, I seem to be having the same problem with your implementation that I was having before... the php side returns a NULL value.

I went ahead and put your example up as a test at http://gateway.southgateaz.org:8004/aes_test.php.  I'm not sure what I'm missing.  I'm just wondering if you've run into this or if you have any pointers.  Thanks!

-Gus

**Comment by brainfoolong** [comment]
Try to put `<?php error_reporting(E_ALL); ini_set('display_errors', 1) ?>` on top of the example file and run it again. Maybe there some hidden errors.

**Comment by gusadelic** [comment]
Actually in the test page I just didn't have the correct path to the aes php file.  It works now.  And I can see that it returns different json values than my application does, so I must be doing something wrong on the javascript side.

**Comment by brainfoolong** [comment]
Ok. So my example is currently working, that's good. You have a good point to start with and you should can easily check what is required in your own script to make it working.

**Comment by gusadelic** [comment]
Yup you're right!  Thanks for taking a look... the problem was that I had not swicthed the passphrase over on the php side to the one I was using in the javascript.  I appreciate your help.  This is what happens when you stare at a screen for too long at the same problem!  haha

**Comment by brainfoolong** [comment]
:+1:
