### ISSUE TITLE
Can you use this without stringify?

### ISSUE THREAD

**Issue by spencerthayer** [brainfoolong/cryptojs-aes-php#11]
I would like to encrypt using PHP and decrypt in JS without the reliance on JSON. Just a plane old AES string. Is that possible?

**Comment by brainfoolong** [comment]
This is not designed to work without JSON. But you can modify it yourself. An idea would be to concat all 3 properties of `j` in a simple string. Maybe you need  base64 encode/decode than.
I will not code this or change this repository, sorry.

**Comment by spencerthayer** [comment]
I wasn't going to ask you to do that for me. I appreciate you letting me know.

**Comment by spencerthayer** [comment]
Out of curiosity what are these three properties: "**ct**","**iv**", and "**s**"?

**Comment by brainfoolong** [comment]
ct = ciphertext
iv = initialization vector
s = salt

**Comment by spencerthayer** [comment]
If the _ciphertext_, _initialization vector_, and _salt_ were publicly available it would be very easy to crack right?

**Comment by spencerthayer** [comment]
For example if the following sting were public accessibility the string could be cracked easier without a passphrase right?
```
{"ct":"SZ+FnZHg0Bk+UOHc39yjuwOEcWmDP5EjaP94AFkD9zTW\/7GeJZ\/pCnEL\/MNoXVe4","iv":"c4a180230e4682eb31fbfa07323673f5","s":"56a3f21df2797a0d"}
```

**Comment by brainfoolong** [comment]
I'm not an expert for aes encryption. But as far as i know, if you miss just one of the 3 variables you cannot decrypt the message. And also with all 3 variables, decryption of AES with brute force requires A LOT of time. Here is a good article about it: http://www.eetimes.com/document.asp?doc_id=1279619

This library use 256bit encryption keys.
