### ISSUE TITLE
web-ftp-client

### ISSUE THREAD

**Issue by wangw-moodys** [brainfoolong/cryptojs-aes-php#16]
Hi, sorry for putting this issue in this page because the project I had issue with had been archived. I really appreciate the project "web-ftp-client" you've done. I was wondering that is there any way I can install the ftp-client in linux server and download the file to local machine? 
Thanks

**Comment by brainfoolong** [comment]
Hi. This client work the same as filezilla or any other locally installed ftp client. You can install it on a device (server, etc...). Than you can download to that machine or upload from that machine. The difference is that this application has a web-based GUI.
