### ISSUE TITLE
JS only / xhr instead of form name

### ISSUE THREAD

**Issue by petrk94** [brainfoolong/cryptojs-aes-php#17]
Hello,

first of all, thanks for that great work, its very hard to find an easily and JS encrypt and PHP decrypt library.
But I have an issue. I would like to use the id of the json input, but due the encryption is handled by jQuery, I dont get it to work.
Instead of sending a form, I want to get it handled by a XHR request and displaying the result without loading another page.
But I dont know what to change in the jquery code to make it work instead with xhr, due I dont get it to use the id of the input field, but always need the name.
Hope you can help and change the jquery code to pure js.

Thanks

Ps. Some code explaining would be fine too ;)

**Comment by brainfoolong** [comment]
Hi, probably i will add some other examples. But there just examples. You don't have to use jquery, you don't have to use forms. You can use everything you have/need.

And i think the 2 functions on PHP and JS side are self-explanatory, no further additions needed as it add no more helpful information.

Your specific case is just one way of many and i have no time to help with your specific case. Sorry.

**Comment by petrk94** [comment]
Thank you for your response.
Unfortunately, the example is just one for the use.
my problem is the need of jquery, my case is nothing special.

The example is fine, but at the end its sending te password non encrypted over POST to the server, I avoid this by removing the name tag and replacing it in jquery by id tag. 
For the XHR sending I need the getelementbyID, but this doesnt work with jquery together, it seems like both are trying to access one element and so jquery is not longer working when I add the id tag to the input field.
Thats why I would like to see it in pure js and understand it better how it works.

**Comment by brainfoolong** [comment]
Please don't get me wrong here. The example are NOT supposed to use 1on1 on your production environment. It is just a one file simple showcase of how PHP and JS wise the script can work.

You don't have to use forms, you don't have to use jquery. All you need are the four functions. All other code is just for the sake of the example.

    CryptoJS.AES.decrypt() // JS
    CryptoJS.AES.encrypt() // JS
    cryptoJsAesEncrypt() // PHP
    cryptoJsAesDecrypt() // PHP

**Comment by petrk94** [comment]
Thanks
