### ISSUE TITLE
no value returned..

### ISSUE THREAD

**Issue by swissonelabs** [brainfoolong/cryptojs-aes-php#22]
I am pretty much copying your example - in php
```
$encrypted_mm = Helper::cryptoJsAesEncrypt('foobar', '123456');
echo $encrypted_mm ;
//which gives me this //{"ct":"pi6z3m0q4jscZKuhXobHoQ==","iv":"6311ee9d122636ac3bf9a0a9abc4b370","s":"f0f067ba05bdb331"}
```

then in js 
```
let encrypted = '{"ct":"pi6z3m0q4jscZKuhXobHoQ==","iv":"6311ee9d122636ac3bf9a0a9abc4b370","s":"f0f067ba05bdb331"}'
        let password = '123456'
        let decrypted = CryptoJS.AES.decrypt(encrypted, password, { format: CryptoJSAesJson }).toString(CryptoJS.enc.Utf8)
        console.log('Decrypted: ' + decrypted)

```
// it is empty..but when I use your foobar encrypted values it works...any idea...fighting for 3 straight hours..

**Comment by brainfoolong** [comment]
Hi. Without seeing what `Helper::cryptoJsAesEncrypt` does, i cannot know what the issue is. Decrypting part looks fine.

**Comment by swissonelabs** [comment]
wow! there is the issue..I copied your code from Stackoverflow and it has passphrase as the first param.
Thanks so much

**Comment by brainfoolong** [comment]
Alright, the code from Github is old and doesn't work with the new examples here.
