### ISSUE TITLE
encrypt in JS and decrypt in PHP gives NULL

### ISSUE THREAD

**Issue by RobinDeeCee** [brainfoolong/cryptojs-aes-php#23]
Hey, sorry to bother you.

I'm implementing you lib in a already exists cordova project project:
JS:
`let password = 'TestEncrypt'

                    var data = new Object();
                    data.mail = CryptoJS.AES.encrypt($(".mailLogin").val(), password, { format: CryptoJSAesJson }).toString();

                    cordova.plugin.http.get('https://...', {}, { data: JSON.stringify(data) }, function(response) {
                        jsonobj = JSON.parse(response.data);
                        M.toast({ html: jsonobj.most_used_message }, 4000) // 4000 is the duration of the toast
                        if (jsonobj.message_code == "200") {
                           
                        }

                    }, function(response) {
                        console.error(response);
                    });`

It's working fine here and I'm receiving It on the severside.
But here it's going wrong here! decrypt function returns a empty value.

PHP:
`$passwordEN = "TestEncrypt";
CryptoJsAes::decrypt($data["mail"],$passwordEN)
`

MORE:
- I don't get any error's
- When I try to encrypt and decrypt something just on the server site it's working fine

Thanks for you time

**Comment by brainfoolong** [comment]
Hi, i see you are sending data with `get`. The encrypted data is not URL safe, so you have to send it with `post`. Propably in your case its `cordova.plugin.http.post`.

**Comment by RobinDeeCee** [comment]
I was to fast, It doesn't work on post resquest.
Should I get a error from you're code if there is something wrong on the SSL side or the is this a cordova issue ?

Thanks for the help

**Comment by brainfoolong** [comment]
There could be so much issues here. But this library does not handle any ssl errors. It's impossible to say what the error here is, but i doubt it's the library itself.
You have to debug it yourself, here are some tipps.
* What you are sending with the request. Make a console.log
* What are you receiving on PHP side, inspect the network request.
* What is in $data, make a var_dump
* Run the same code but with hardcoded values to make sure the library itself can work correctly.

**Comment by RobinDeeCee** [comment]
I send a mail to the support from my webserver, to see if nothing is wrong there.
I'm also checking the code, If I find something wrong, I will let you know or send a pull request.

Thanks for the info !
