### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by jjsainzc** [brainfoolong/cryptojs-aes-php#24]
I encrypt in JS and decrypt in PHP decrypt value return empty

**Comment by brainfoolong** [comment]
Hi, without all relevant code that you use, i cannot help you.

**Comment by jjsainzc** [comment]
Im using your example code

<?php

use Nullix\CryptoJsAes\CryptoJsAes;

require __DIR__ . "/../src/CryptoJsAes.php";

$encrypted =
'{"ct":"yd4E5Ww/J3UBA3o6mdY0gQ==","iv":"2df678669c71d4bbbe4b837dd2be3b54","s":"db8666deaec582d3"}';
// <- Encrypted with JS code
$password = "123456";
$decrypted = CryptoJsAes::decrypt($encrypted, $password);

echo "Encrypted: " . $encrypted . "\n";
echo "Decrypted: " . print_r($decrypted, true) . "\n";


Muchos saludos
Jorge Jesus Sainz Casalla

Freelance senior software developement and consultant.

**Comment by brainfoolong** [comment]
You are right, in this case the example was wrong. I've updated the example code. 
The difference is, when encrypting in JS, you need to `JSON.stringify` the value before passing to CryptoJS.

Fixed line in example:

     let encrypted = CryptoJS.AES.encrypt(JSON.stringify(valueToEncrypt), password, { format: CryptoJSAesJson }).toString()

**Comment by jjsainzc** [comment]
Thanks for your help

Jorge Jesus Sainz Casalla

Freelance senior software developement and consultant.
