### ISSUE TITLE
decrypt php return null or empty

### ISSUE THREAD

**Issue by maycoldsm1234** [brainfoolong/cryptojs-aes-php#27]
the decrypt function returns empty when the value is generated from javascript

php:
public static function decrypt($jsonStr)
    {
        $json = json_decode($jsonStr, true);
        $salt = hex2bin($json["s"]);
        $iv = hex2bin($json["iv"]);
        $ct = base64_decode($json["ct"]);
        $concatedPassphrase = env('CRYPTO_KEY') . $salt;
        $md5 = [];
        $md5[0] = md5($concatedPassphrase, true);
        $result = $md5[0];
        for ($i = 1; $i < 3; $i++) {
            $md5[$i] = md5($md5[$i - 1] . $concatedPassphrase, true);
            $result .= $md5[$i];
        }
        $key = substr($result, 0, 32);
        $data = openssl_decrypt($ct, 'aes-256-cbc', $key, true, $iv);
        return json_decode($data, true);
    }

javascript:

var CryptoJSAesJson = {
      stringify: function (cipherParams) {
        var j = { ct: cipherParams.ciphertext.toString(CryptoJS.enc.Base64), iv:'', s:'' }
        if (cipherParams.iv) j.iv = cipherParams.iv.toString()
        if (cipherParams.salt) j.s = cipherParams.salt.toString()
        return (JSON.stringify(j))
      },
      parse: function (jsonStr) {
        var j = JSON.parse((jsonStr))
        var cipherParams = CryptoJS.lib.CipherParams.create({ ciphertext: CryptoJS.enc.Base64.parse(j.ct) })
        if (j.iv) cipherParams.iv = CryptoJS.enc.Hex.parse(j.iv)
        if (j.s) cipherParams.salt = CryptoJS.enc.Hex.parse(j.s)
        return cipherParams
      }
    }

    var encrypted = CryptoJS.AES.encrypt(JSON.stringify('123456'), environment.keyCrypt, { format: CryptoJSAesJson }).toString()

**Comment by brainfoolong** [comment]
Hi, please post complete reproducable example that shows the exact problem. With the code you've posted i cannot help debugging. Also it seems that you use an old version of this library. At least the JS part is old, when you compare it with current examples.

**Comment by brainfoolong** [comment]
I close this issue.
