### ISSUE TITLE
toString(CryptoJS.enc.Utf8))

### ISSUE THREAD

**Issue by RoxDevvv** [brainfoolong/cryptojs-aes-php#29]
Can use toString(CryptoJS.enc.Utf8)) ? Just going to ecrypt and decrypt w text with arabic france letters i wanna make sure if that function exist

**Comment by brainfoolong** [comment]
Yes, but i also recommend just to try it out yourself.
I quick test:

![image](https://user-images.githubusercontent.com/1684236/164148773-6685d9e2-f65a-41e4-9e75-655d9fcf5044.png)

You see, it does handle UTF8 properly.

**Comment by RoxDevvv** [comment]
Thank you 💓
