### ISSUE TITLE
PHP miminum version requirement ?

### ISSUE THREAD

**Issue by AndreiTelteu** [brainfoolong/cryptojs-aes-php#3]
Hi.
I tried to run this library on PHP 5.3 and it didn't failed, but it didn't worked well neither.
What is the minimum version that this library/function requires ?
Thanks.

**Comment by brainfoolong** [comment]
PHP 5.3 is minimum, so it should work for you. 
What exactly is your problem? Enable `<?php error_reporting(E_ALL); ?>` on top of your testpage to see all errors.
Also it require PHP with openssl support, it's default on most machines, maybe that is the problem.
http://php.net/manual/en/openssl.installation.php

**Comment by brainfoolong** [comment]
PS: Also it require PHP with openssl support, it's default on most machines, maybe that is the problem.
http://php.net/manual/en/openssl.installation.php

**Comment by AndreiTelteu** [comment]
I was working on wordpress, php 5.3, and i got a blank page. I tried error reporting, but it was still a blank page. That must be caused by a problem in my code.
I acomplished what i needed with base64 encode in php and decode in js.
But you shoud put the minimum php requirement in readme, in case that someone else has a problem.
Thanks :)

**Comment by brainfoolong** [comment]
Done. Thx. Closed.
