### ISSUE TITLE
Not Working in Safari browser. Is there any solutions. 

### ISSUE THREAD

**Issue by sanketit** [brainfoolong/cryptojs-aes-php#30]

**Comment by brainfoolong** [comment]
Hi, without any example code, error message, logs, etc... it is impossible to give an answer. Please provide an example code. Also post what exact Safari version you use and on what OS you try this.

**Comment by sanketit** [comment]
Thanks for reply.

We are checking on safari version 15.4 (15613.1.17.1.13,15613) and MAC OS for encrypt username and password.

Here is error details we are facing.

Uncaught SyntaxError: expected property name, got '{' in  cryptojs-aes.min.js

**Comment by brainfoolong** [comment]
Ok. Looks like you serving a corrupt `cryptojs-aes.min.js` - Have you verified that the file what your webserver does serve is the same as in this repository?

**Comment by brainfoolong** [comment]
Additionally, it can also be just the way you call it. An example code really will be helpful to debug further.
