### ISSUE TITLE
Form Reset Not working after form submit using crypto js

### ISSUE THREAD

**Issue by sanketit** [brainfoolong/cryptojs-aes-php#31]
Hello, there we are using crypto js to encrypt username and password in login. The code is as follows.

 var username = $("#username").val();
  var password1 = $("#password").val();
  var password = "123456";
  username = CryptoJSAesJson.encrypt(username, password);
  password1 = CryptoJSAesJson.encrypt(password1, password);
  $("#username").val(username);
  $("#password").val(password1);
  form.submit();
  $('#login_form')[0].reset();

but here reset is not working on the Mac device. Can you please check and let me help.

Thanks In advance!

**Comment by brainfoolong** [comment]
Hi!

This is no issue of this library. It seems you use jquery, so you have to check there, not here.
The only lines here that are relevant to this repository is

```
username = CryptoJSAesJson.encrypt(username, password);
password1 = CryptoJSAesJson.encrypt(password1, password);
```
