### ISSUE TITLE
is there any way to  encrypt image using cryptojs-aes-php?

### ISSUE THREAD

**Issue by Sourovahmad** [brainfoolong/cryptojs-aes-php#36]

**Comment by brainfoolong** [comment]
Hi. It's up to you what data you want encrypt.  Make the image base64 and encrypt that value.

**Comment by Sourovahmad** [comment]
> Hi. It's up to you what data you want encrypt. Make the image base64 and encrypt that value.

hi thank you so much for your reply. could you please give me an example of encryption and decryption of image ? i will really appreciate your help.

**Comment by brainfoolong** [comment]
Sorry, that is out of scope for this library. You will find tons of tutorials how to convert image data to a base64 string.

**Comment by Sourovahmad** [comment]
> base64

thank you for your time.
