### ISSUE TITLE
Security vulnerability responsible disclosure

### ISSUE THREAD

**Issue by lukigruszka** [brainfoolong/cryptojs-aes-php#37]
Hello,

CERT PL found a security vulnerability in this repository. How can we report this privately? We don't see any security policy describing how such vulnerabilities should be reported.

**Comment by brainfoolong** [comment]
You can contact me directly in my Slack channel that you can find on https://framelix.com/getstarted/issues

**Comment by brainfoolong** [comment]
PS: If the issue was with the included library CryptoJS, this now has been updated to the most recent version.
