### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by paul-piro** [brainfoolong/cryptojs-aes-php#4]
it's not working js encrypts but the php side it's not doing anyhing

**Comment by brainfoolong** [comment]
This ain't helpful, what exactly is the problem? Any errors? Please provide more information.
Have you tried the example files?

**Comment by paul-piro** [comment]
i installed the examples but js-to-php when you submit the data php cannot decrypt it

**Comment by brainfoolong** [comment]
Yes, but have you any errors, have you viewed the source code after you've submitted the example? The most people with such a problem don't have openssl support installed and than you have a error like `undefined function` in the page source code after submitting the form.

**Comment by paul-piro** [comment]
Yes i have them all installed and i checked for errors it seems that one
param is send witn ' "...." ' and php cannot decode it

**Comment by brainfoolong** [comment]
There should be any error on the page, maybe hidden in the source code but when it did not work there really must be some error. I've tested it right now with PHP 5.4+ and PHP 7 and it work fine for both.

**Comment by paul-piro** [comment]
i unzipped the lib here, take a look in the exaples js-to-php see when you
submit it will not decode it, server is using php 5.4 and all the
dependencies are installed

http://microstockr.com/1/

**Comment by brainfoolong** [comment]
Ok i've tested it, there is an error after submitted the form, you see it when you show the source code of the page.
`Call to undefined function hex2bin() in <b>/home/piromanu/www/microstockr.com/1/cryptojs-aes.php</b> on line <b>19</b><br />`
That seems that you don't have PHP 5.4 or higher because the function hex2bin is only available in PHP 5.4 and later.
http://php.net/manual/en/function.hex2bin.php

**Comment by paul-piro** [comment]
oh that means Dreamhost doesn't have hex2bin

Thank you very much i think you can close it

PS: you should put these 2 functions in the scripts for future use and use
those instead of native php

```
function hex2str($hex) {
    return pack("H*", $hex);
}

function str2hex($str) {
    return array_shift(unpack('H*', $str));
}
```

**Comment by brainfoolong** [comment]
Ok thx. Anyway, i prefer to depend on native php functions, it's weird that such a simple function is disabled on your host and the whole openssl stuff isn't :)

**Comment by paul-piro** [comment]
:)) yeah there are other functions disabled too like getallheaders()
