### ISSUE TITLE
javascript code is really slow

### ISSUE THREAD

**Issue by minttest** [brainfoolong/cryptojs-aes-php#5]
Hi, thanks for this repo. it's great. I found another package that when I use it, it takes 19 seconds to be decrypt a long text, and yours do it in 17 seconds, and because of this 2 secondes I wanna use yours.
1- But my question is that can you incresase it's speed? it's too slow yet.
2-this decrypting takes 17 seconds in chrome but 9 seconcs in firefox, why this happens?
3- what is that "iv":"XXX","s":"XXX" at the last of code? (it's because of  {format: CryptoJSAesJson}).toString(CryptoJS.enc.Utf8) )
4- what is the blocksize in your AES code? 128,192 or 256? and we can't select blocksize! Is it safe enough? (I use a secure password)
5- when I deccypt a gzcompressed text by your code, why there is no difference in time between compressed text and plain text? previous package that I used decypts the compressed text in 17 seconds and the plain text in 24 seconds!

**Comment by brainfoolong** [comment]
1,2: Javascript side depends all an CyptoJS library, i cannot do or answer anything, more info -> https://code.google.com/p/crypto-js/

3: IV = Initialization Vector
S = Random Salt
More information here: https://code.google.com/p/crypto-js/#AES

4: The method is: aes-256-cbc

In general, CryptoJS default settings are used and the PHP functions are built to work with the CryptoJS defaults. You can improve it if you need it, i cannot say what is more safe or better because i am not that good in crypto things.

Hope this answer is enough.

**Comment by minttest** [comment]
thank you. yes the answer was enough, but I have a problem in encrypting in js and decrypting in PHP. (vice versa was ok)

my code in JS:

my_password_var='123456';
data = CryptoJS.AES.encrypt(JSON.stringify(data), my_password_var, {format: CryptoJSAesJson}).toString();

---

my code in PHP:

$password = '123456';
$data = cryptoJsAesDecrypt($password, $_POST["data"]);

---

and the data transfers using this ajax code:

$.ajax({
       type: "POST",
       url: "destination.php",
       data: data,
       success: function(msg){

```
        if (msg.error) {
        // error
    } else {
```

// rest of code

```
   }
   }
 });
```

---

what's wrong in my codes or yours that the $data in PHP is empty?! ( the content is UTF-8)

**Comment by brainfoolong** [comment]
There many errors in your code, i don't want to point out every single error, will take too long.
The best is, take the example file and re-built it to your needs, always test and test while you modify your code.
Basically you have JS errors/warnings in your code that need to be fixed (See F12 Console in your browser)
1. `var my_password_var='123456';` not `my_password_var='123456';`
2. `data: data` will not work, double sided same variable. Rename your data variable name to a more specific name like `encryptedData`, than you have `data : encryptedData`

**Comment by brainfoolong** [comment]
I'll close this ticket because your basic question is solved in my opinion. All other stuff is pure JS/PHP and you can fix it all with clean code.
