### ISSUE TITLE
Getting error on  parsing JSON from php file

### ISSUE THREAD

**Issue by alaksandarjesus** [brainfoolong/cryptojs-aes-php#6]
I am getting JSON error while i pass data from php file.
**HTML**

```
   <script src="cryptojs-aes-php-master/example/aes.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0-alpha1/jquery.min.js"></script>
  <script src="cryptojs-aes-php-master/aes-json-format.js"></script>
```

**PHP File**

```
$encodeanswer[]=htmlentities(cryptoJsAesEncrypt($answer,"123"))
```

**JS File**

```
console.log(value);
```

 //{&quot;ct&quot;:&quot;9i4gxztr7W7W0sPFKo1SKA==&quot;,&quot;iv&quot;:&quot;5fba99d002577c64ce4421a979d49f40&quot;,&quot;s&quot;:&quot;fe836ae24c8ca962&quot;}

```
var parsedvalue = value.replace(/&quot;/g,'"')
console.log(parsedvalue);
```

//{ ct: "nPR3gyDA5Q6Qra1Py9GtAA==", iv: "7e10905af0f4d0ba3fb2cfeb5d77ae8e", s: "ee20cfb01b5b25b6" }

```
console.log(JSON.parse(CryptoJS.AES.decrypt(parsedvalue,"123", {format: CryptoJSAesJson}).toString(CryptoJS.enc.Utf8)));
```

 //SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

Note: I tested your example and it populating data in input box.

**Comment by brainfoolong** [comment]
Remove `htmlentities` and  `value.replace`.
Furthermore i don't really understand your way to go here. You encrypt data in PHP, than you replace htmlentities, than you replace it back on JS side, than you try to decrypt it AND you try to parse it, the `decrypt` already do the parse for you.
The real way is: PHP encrypt, JS decrypt, without any step between, no extra `htmlentities`, no extra `JSON.stringify` or `JSON.parse`

**Comment by alaksandarjesus** [comment]
Hi. Thanks for reply. I cleared off the error.  I  php file its key and phrase and js file its phrase and key. Why this jnverted combination? 

Alaksandar
+91-9952762769

**Comment by brainfoolong** [comment]
Em... Don't know, never thought about that :)
I close this.
