### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by fcarstensen** [brainfoolong/cryptojs-aes-php#8]
I encrypted an array in php and want to decrypt the response data with js.

cryptoJsAesEncrypt('pass', some_data); = ok

JSON.parse(CryptoJS.AES.decrypt(some_encrypted_data, "pass", {format: CryptoJSAesJson}).toString(CryptoJS.enc.Utf8)) = failed

TypeError: Cannot read property 'length' of undefined
    at Object.u.enc.Base64.parse (aes.js:14)
    at Object.CryptoJSAesJson.parse (app.js:558)
    at Object.d.SerializableCipher.l.extend._parse (aes.js:30)
    at Object.d.PasswordBasedCipher.a.extend.decrypt (aes.js:31)
    at Object.decrypt (aes.js:25)

Any ideas?

**Comment by brainfoolong** [comment]
Please post all code, without knowing the "some_encrypted_data" and "some_data" i cannot help you.

**Comment by fcarstensen** [comment]
I'm sorry, you're right, here comes the code:

``` php
private function cryptoJsAesEncrypt($passphrase, $value)
{
    $salt = openssl_random_pseudo_bytes(8);
    $salted = '';
    $dx = '';
    while (strlen($salted) < 48) {
        $dx = md5($dx.$passphrase.$salt, true);
        $salted .= $dx;
    }
    $key = substr($salted, 0, 32);
    $iv  = substr($salted, 32,16);
    $encrypted_data = openssl_encrypt(json_encode($value), 'aes-256-cbc', $key, true, $iv);
    $data = array("ct" => base64_encode($encrypted_data), "iv" => bin2hex($iv), "s" => bin2hex($salt));
    return json_encode($data);
}

private function getTopClanToonsCount()
{    
    $sql = "SELECT COUNT( t.game_id ) AS toon_amount, t.toon_clan
            FROM toon t
            WHERE t.deleted =0
            AND t.toon_clan != ''
            GROUP BY t.toon_clan
            ORDER BY toon_amount DESC 
            LIMIT 5";

    $stmt = DB::getInstance()->prepare($sql);
    $stmt->execute();

    $clanCount = $stmt->fetchAll();
        if (is_array($clanCount))
        {
            return $this->cryptoJsAesEncrypt('test123', $clanCount);
        }
    return null;
}
```

``` javascript
      function getTopClanToons(){  
      $http.post("../some_url.php?action=getTopClanToonsCount").success(function(data){   

            var CryptoJSAesJson = {
                stringify: function (cipherParams) {
                    var j = {ct: cipherParams.ciphertext.toString(CryptoJS.enc.Base64)};
                    if (cipherParams.iv) j.iv = cipherParams.iv.toString();
                    if (cipherParams.salt) j.s = cipherParams.salt.toString();
                    return JSON.stringify(j);
                },
                parse: function (jsonStr) {
                    var j = JSON.parse(jsonStr);
                    var cipherParams = CryptoJS.lib.CipherParams.create({ciphertext: CryptoJS.enc.Base64.parse(j.ct)});
                    if (j.iv) cipherParams.iv = CryptoJS.enc.Hex.parse(j.iv)
                    if (j.s) cipherParams.salt = CryptoJS.enc.Hex.parse(j.s)
                    return cipherParams;
                }
            }

            console.log(JSON.parse(CryptoJS.AES.decrypt(data, "test123", {format: CryptoJSAesJson}).toString(CryptoJS.enc.Utf8)));
            //$scope.topClanToonsCount = JSON.parse(CryptoJS.AES.decrypt(data, "test", {format: CryptoJSAesJson}).toString(CryptoJS.enc.Utf8));
            //$scope.topClanToonsCount = data;
           });
      }; 
```

I hope this will help you... and finally me ;)

**Comment by fcarstensen** [comment]
This is a php result after the cryptoJsAesEncrypt:

```
"{\"ct\":\"OBPmdQVbGuxXVl7MBZCntJwVnDFWnyqIif2B1YyH7BVn4eROzq4i0cus5g3+ZPDTBQbcSe+blmYsc9p7VYb98koVUy06qjrLXr9IPjt9uR\\\/o4aFWd1tdlLQHvtE90D+b\",\"iv\":\"ab044b14232442e4e48f06c195e3b7b4\",\"s\":\"39b096acaba76884\"}"
```

**Comment by brainfoolong** [comment]
What data is in `data` of the JS callback, do a `console.log(data)` and post the result.

**Comment by fcarstensen** [comment]
```
"{\"ct\":\"dxZkCuq\\\/H7YqQs3E5lrs9ZZ2c9M3O5TCL1Bdtnm\\\/1mkOyEVUOtNk8ZVNPnqp1Ca966dRjOV9k4FT+z7TpEmeYFZv2I1L+q6fWXIIQQIV\\\/m4RiA2V8MF4VEq7y5QBpteN\",\"iv\":\"5c0757952300fe019196d02a830c0af2\",\"s\":\"0c4a63c4dd46ac5b\"}"
```

**Comment by fcarstensen** [comment]
![console_log](https://cloud.githubusercontent.com/assets/12542720/12263315/5a69fbe4-b92e-11e5-82c4-6ccbe8507212.jpg)
may be this is the break after the "

**Comment by brainfoolong** [comment]
When i do just this, it works perfectly fine. So i guess you have some problems with your returned data from the ajax request, a line break or whatever.

```
var str = "{\"ct\":\"dxZkCuq\\\/H7YqQs3E5lrs9ZZ2c9M3O5TCL1Bdtnm\\\/1mkOyEVUOtNk8ZVNPnqp1Ca966dRjOV9k4FT+z7TpEmeYFZv2I1L+q6fWXIIQQIV\\\/m4RiA2V8MF4VEq7y5QBpteN\",\"iv\":\"5c0757952300fe019196d02a830c0af2\",\"s\":\"0c4a63c4dd46ac5b\"}";
console.log(JSON.parse(CryptoJS.AES.decrypt(str, "test123", {format: CryptoJSAesJson}).toString(CryptoJS.enc.Utf8)));
```

**Comment by brainfoolong** [comment]
Or you mabe doesn't have included cryptojs properly in your page, what does `console.log(CryptoJS.AES.decrypt)` give you?

**Comment by fcarstensen** [comment]
I have included the following js files:
    aes.js
    aes-json-format.js

The result of console.log(CryptoJS.AES.decrypt) is:
function (b,k,d){return("string"==typeof k?c:a).decrypt(e,b,k,d)}

**Comment by brainfoolong** [comment]
so, what you get when you do just this for a test case on your page?
https://github.com/brainfoolong/cryptojs-aes-php/issues/8#issuecomment-170894356

i don't think that this library or cryptojs have a problem here.

**Comment by fcarstensen** [comment]
Then I get the correct data:

```
[Object, Object]
0: Object
toon_amount: "3"
toon_clan: "testclan"
__proto__: Object
1: Object
toon_amount: "1"
toon_clan: "neuclan"
__proto__: Object
length: 2
__proto__: Array[0]
```

I think it's the break after the "
but I have no idea to fix it...

**Comment by brainfoolong** [comment]
Have you already tried just running the example files without modification?
If that work than i cannot help you in this specific task because it obviously as a bug in your code.

**Comment by fcarstensen** [comment]
Ok, now I tried some things... on php side at the return value with json_encode / decode and escape characters... nothing. Then I played with some things on the client side at the js function. A few more console.logs and I found a solution.

```
$scope.topClanToonsCount = JSON.parse(CryptoJS.AES.decrypt(JSON.parse(data), "test123", {format: CryptoJSAesJson}).toString(CryptoJS.enc.Utf8));
```

JSON.parse(data) was the solution.

brainfoolong thanks for your help and for pushing me to dig deeper in the code

**Comment by brainfoolong** [comment]
This is weird, It should not be required to double `JSON.parse` the encrypted string.
Do you maybe have a second `json_encode` in your code outside of `cryptoJsAesEncrypt`

**Comment by fcarstensen** [comment]
Yes, I do:

```
json_encode($app->handleAction($_REQUEST)
```

This issue can be closed.

**Comment by brainfoolong** [comment]
Ok, that's the bug :) You don't have to do this, the `json_encode` inside the `cryptoJsAesEncrypt` already does it. Closed.
